// CollectorService defines the gRPC interface between route-beacon collectors
// and the central aggregation server. Collectors initiate all connections;
// authentication relies on private-CA mTLS.
//
// Data flow:
//   1. Collector registers itself and its router sessions (Register).
//   2. Collector sends a full route snapshot on connect, then incremental
//      delta updates over a bidirectional stream (SyncRoutes).
//   3. Central pushes diagnostic commands to the collector (SubscribeCommands).
//   4. Collector streams command output back to central (ReportCommandResult).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/routebeacon/v1/collector_service.proto

package routebeaconv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollectorService_Register_FullMethodName            = "/routebeacon.v1.CollectorService/Register"
	CollectorService_SyncRoutes_FullMethodName          = "/routebeacon.v1.CollectorService/SyncRoutes"
	CollectorService_SubscribeCommands_FullMethodName   = "/routebeacon.v1.CollectorService/SubscribeCommands"
	CollectorService_ReportCommandResult_FullMethodName = "/routebeacon.v1.CollectorService/ReportCommandResult"
)

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CollectorService is the single gRPC service exposed by central.
// Every RPC is initiated by the collector (client); the server never dials
// back, which keeps firewall rules simple and NAT-friendly.
type CollectorServiceClient interface {
	// Register is called once when a collector starts up. It announces the
	// collector's identity and the set of router sessions it manages. Central
	// validates the request and returns an acceptance status.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// SyncRoutes is a bidirectional stream used for all route data exchange.
	// On initial connect the collector sends a full snapshot bracketed by
	// BeginSnapshot / EndSnapshot messages. After the snapshot completes,
	// the collector sends incremental RouteUpdate messages as BGP changes
	// occur. Central may send back-pressure signals (Throttle) or snapshot
	// acknowledgments on the return channel.
	SyncRoutes(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RouteMessage, SyncControl], error)
	// SubscribeCommands opens a server-side stream through which central
	// pushes diagnostic commands (ping, traceroute, etc.) to the collector.
	// The collector keeps this stream open for the lifetime of its connection.
	SubscribeCommands(ctx context.Context, in *CollectorIdentity, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DiagnosticCommand], error)
	// ReportCommandResult is a client-side stream used by the collector to
	// send the output of a diagnostic command back to central. Results arrive
	// as a series of chunks (individual ping replies, traceroute hops) and
	// are terminated by either a CommandComplete or CommandError message.
	ReportCommandResult(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CommandResultChunk, CommandAck], error)
}

type collectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorServiceClient(cc grpc.ClientConnInterface) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, CollectorService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) SyncRoutes(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RouteMessage, SyncControl], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[0], CollectorService_SyncRoutes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RouteMessage, SyncControl]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_SyncRoutesClient = grpc.BidiStreamingClient[RouteMessage, SyncControl]

func (c *collectorServiceClient) SubscribeCommands(ctx context.Context, in *CollectorIdentity, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DiagnosticCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[1], CollectorService_SubscribeCommands_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CollectorIdentity, DiagnosticCommand]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_SubscribeCommandsClient = grpc.ServerStreamingClient[DiagnosticCommand]

func (c *collectorServiceClient) ReportCommandResult(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CommandResultChunk, CommandAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[2], CollectorService_ReportCommandResult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandResultChunk, CommandAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_ReportCommandResultClient = grpc.ClientStreamingClient[CommandResultChunk, CommandAck]

// CollectorServiceServer is the server API for CollectorService service.
// All implementations must embed UnimplementedCollectorServiceServer
// for forward compatibility.
//
// CollectorService is the single gRPC service exposed by central.
// Every RPC is initiated by the collector (client); the server never dials
// back, which keeps firewall rules simple and NAT-friendly.
type CollectorServiceServer interface {
	// Register is called once when a collector starts up. It announces the
	// collector's identity and the set of router sessions it manages. Central
	// validates the request and returns an acceptance status.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// SyncRoutes is a bidirectional stream used for all route data exchange.
	// On initial connect the collector sends a full snapshot bracketed by
	// BeginSnapshot / EndSnapshot messages. After the snapshot completes,
	// the collector sends incremental RouteUpdate messages as BGP changes
	// occur. Central may send back-pressure signals (Throttle) or snapshot
	// acknowledgments on the return channel.
	SyncRoutes(grpc.BidiStreamingServer[RouteMessage, SyncControl]) error
	// SubscribeCommands opens a server-side stream through which central
	// pushes diagnostic commands (ping, traceroute, etc.) to the collector.
	// The collector keeps this stream open for the lifetime of its connection.
	SubscribeCommands(*CollectorIdentity, grpc.ServerStreamingServer[DiagnosticCommand]) error
	// ReportCommandResult is a client-side stream used by the collector to
	// send the output of a diagnostic command back to central. Results arrive
	// as a series of chunks (individual ping replies, traceroute hops) and
	// are terminated by either a CommandComplete or CommandError message.
	ReportCommandResult(grpc.ClientStreamingServer[CommandResultChunk, CommandAck]) error
	mustEmbedUnimplementedCollectorServiceServer()
}

// UnimplementedCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectorServiceServer struct{}

func (UnimplementedCollectorServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedCollectorServiceServer) SyncRoutes(grpc.BidiStreamingServer[RouteMessage, SyncControl]) error {
	return status.Error(codes.Unimplemented, "method SyncRoutes not implemented")
}
func (UnimplementedCollectorServiceServer) SubscribeCommands(*CollectorIdentity, grpc.ServerStreamingServer[DiagnosticCommand]) error {
	return status.Error(codes.Unimplemented, "method SubscribeCommands not implemented")
}
func (UnimplementedCollectorServiceServer) ReportCommandResult(grpc.ClientStreamingServer[CommandResultChunk, CommandAck]) error {
	return status.Error(codes.Unimplemented, "method ReportCommandResult not implemented")
}
func (UnimplementedCollectorServiceServer) mustEmbedUnimplementedCollectorServiceServer() {}
func (UnimplementedCollectorServiceServer) testEmbeddedByValue()                          {}

// UnsafeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServiceServer will
// result in compilation errors.
type UnsafeCollectorServiceServer interface {
	mustEmbedUnimplementedCollectorServiceServer()
}

func RegisterCollectorServiceServer(s grpc.ServiceRegistrar, srv CollectorServiceServer) {
	// If the following call panics, it indicates UnimplementedCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectorService_ServiceDesc, srv)
}

func _CollectorService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_SyncRoutes_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).SyncRoutes(&grpc.GenericServerStream[RouteMessage, SyncControl]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_SyncRoutesServer = grpc.BidiStreamingServer[RouteMessage, SyncControl]

func _CollectorService_SubscribeCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CollectorIdentity)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollectorServiceServer).SubscribeCommands(m, &grpc.GenericServerStream[CollectorIdentity, DiagnosticCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_SubscribeCommandsServer = grpc.ServerStreamingServer[DiagnosticCommand]

func _CollectorService_ReportCommandResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).ReportCommandResult(&grpc.GenericServerStream[CommandResultChunk, CommandAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_ReportCommandResultServer = grpc.ClientStreamingServer[CommandResultChunk, CommandAck]

// CollectorService_ServiceDesc is the grpc.ServiceDesc for CollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routebeacon.v1.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _CollectorService_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncRoutes",
			Handler:       _CollectorService_SyncRoutes_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeCommands",
			Handler:       _CollectorService_SubscribeCommands_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReportCommandResult",
			Handler:       _CollectorService_ReportCommandResult_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/routebeacon/v1/collector_service.proto",
}
