// CollectorService defines the gRPC interface between route-beacon collectors
// and the central aggregation server. Collectors initiate all connections;
// authentication relies on private-CA mTLS.
//
// Data flow:
//   1. Collector registers itself and its router sessions (Register).
//   2. Collector sends a full route snapshot on connect, then incremental
//      delta updates over a bidirectional stream (SyncRoutes).
//   3. Central pushes diagnostic commands to the collector (SubscribeCommands).
//   4. Collector streams command output back to central (ReportCommandResult).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/routebeacon/v1/collector_service.proto

package routebeaconv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RouteAction indicates whether a route is being advertised or removed.
type RouteAction int32

const (
	RouteAction_ROUTE_ACTION_UNSPECIFIED RouteAction = 0
	RouteAction_ADD                      RouteAction = 1
	RouteAction_WITHDRAW                 RouteAction = 2
)

// Enum value maps for RouteAction.
var (
	RouteAction_name = map[int32]string{
		0: "ROUTE_ACTION_UNSPECIFIED",
		1: "ADD",
		2: "WITHDRAW",
	}
	RouteAction_value = map[string]int32{
		"ROUTE_ACTION_UNSPECIFIED": 0,
		"ADD":                      1,
		"WITHDRAW":                 2,
	}
)

func (x RouteAction) Enum() *RouteAction {
	p := new(RouteAction)
	*p = x
	return p
}

func (x RouteAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_routebeacon_v1_collector_service_proto_enumTypes[0].Descriptor()
}

func (RouteAction) Type() protoreflect.EnumType {
	return &file_proto_routebeacon_v1_collector_service_proto_enumTypes[0]
}

func (x RouteAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteAction.Descriptor instead.
func (RouteAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{0}
}

// AddressFamily identifies the IP version of a route prefix.
type AddressFamily int32

const (
	AddressFamily_ADDRESS_FAMILY_UNSPECIFIED AddressFamily = 0
	AddressFamily_IPV4                       AddressFamily = 1
	AddressFamily_IPV6                       AddressFamily = 2
)

// Enum value maps for AddressFamily.
var (
	AddressFamily_name = map[int32]string{
		0: "ADDRESS_FAMILY_UNSPECIFIED",
		1: "IPV4",
		2: "IPV6",
	}
	AddressFamily_value = map[string]int32{
		"ADDRESS_FAMILY_UNSPECIFIED": 0,
		"IPV4":                       1,
		"IPV6":                       2,
	}
)

func (x AddressFamily) Enum() *AddressFamily {
	p := new(AddressFamily)
	*p = x
	return p
}

func (x AddressFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_routebeacon_v1_collector_service_proto_enumTypes[1].Descriptor()
}

func (AddressFamily) Type() protoreflect.EnumType {
	return &file_proto_routebeacon_v1_collector_service_proto_enumTypes[1]
}

func (x AddressFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressFamily.Descriptor instead.
func (AddressFamily) EnumDescriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{1}
}

// ASPathSegmentType distinguishes ordered sequences from unordered sets
// in the AS_PATH.
type ASPathSegmentType int32

const (
	ASPathSegmentType_AS_PATH_SEGMENT_TYPE_UNSPECIFIED ASPathSegmentType = 0
	ASPathSegmentType_AS_SET                           ASPathSegmentType = 1
	ASPathSegmentType_AS_SEQUENCE                      ASPathSegmentType = 2
)

// Enum value maps for ASPathSegmentType.
var (
	ASPathSegmentType_name = map[int32]string{
		0: "AS_PATH_SEGMENT_TYPE_UNSPECIFIED",
		1: "AS_SET",
		2: "AS_SEQUENCE",
	}
	ASPathSegmentType_value = map[string]int32{
		"AS_PATH_SEGMENT_TYPE_UNSPECIFIED": 0,
		"AS_SET":                           1,
		"AS_SEQUENCE":                      2,
	}
)

func (x ASPathSegmentType) Enum() *ASPathSegmentType {
	p := new(ASPathSegmentType)
	*p = x
	return p
}

func (x ASPathSegmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ASPathSegmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_routebeacon_v1_collector_service_proto_enumTypes[2].Descriptor()
}

func (ASPathSegmentType) Type() protoreflect.EnumType {
	return &file_proto_routebeacon_v1_collector_service_proto_enumTypes[2]
}

func (x ASPathSegmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ASPathSegmentType.Descriptor instead.
func (ASPathSegmentType) EnumDescriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{2}
}

// RegisterRequest carries everything central needs to know about a collector
// and the BGP router sessions it manages.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique identifier for this collector instance.
	CollectorId string `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	// Human-readable location label (e.g. "Frankfurt, DE" or "dc-fra-01").
	LocationName string `protobuf:"bytes,2,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	// The set of BGP sessions this collector monitors.
	RouterSessions []*RouterSession `protobuf:"bytes,3,rep,name=router_sessions,json=routerSessions,proto3" json:"router_sessions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *RegisterRequest) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *RegisterRequest) GetRouterSessions() []*RouterSession {
	if x != nil {
		return x.RouterSessions
	}
	return nil
}

// RouterSession describes a single BGP session that the collector reads
// routes from (via BMP, a local RIB dump, etc.).
type RouterSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier unique within this collector.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Human-readable name shown in the looking glass UI.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Autonomous System Number of the peer router.
	Asn uint32 `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	// IP address of the BGP neighbor (IPv4 or IPv6, text form).
	NeighborAddress string `protobuf:"bytes,4,opt,name=neighbor_address,json=neighborAddress,proto3" json:"neighbor_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouterSession) Reset() {
	*x = RouterSession{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterSession) ProtoMessage() {}

func (x *RouterSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterSession.ProtoReflect.Descriptor instead.
func (*RouterSession) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{1}
}

func (x *RouterSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RouterSession) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RouterSession) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *RouterSession) GetNeighborAddress() string {
	if x != nil {
		return x.NeighborAddress
	}
	return ""
}

// RegisterResponse tells the collector whether central accepted its
// registration.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the collector was successfully registered.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Optional human-readable status or rejection reason.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RouteMessage is the envelope sent by the collector on the SyncRoutes
// stream. Exactly one of the oneof fields is set per message.
type RouteMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RouteMessage_BeginSnapshot
	//	*RouteMessage_RouteUpdate
	//	*RouteMessage_EndSnapshot
	Payload       isRouteMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMessage) Reset() {
	*x = RouteMessage{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMessage) ProtoMessage() {}

func (x *RouteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMessage.ProtoReflect.Descriptor instead.
func (*RouteMessage) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{3}
}

func (x *RouteMessage) GetPayload() isRouteMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RouteMessage) GetBeginSnapshot() *BeginSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*RouteMessage_BeginSnapshot); ok {
			return x.BeginSnapshot
		}
	}
	return nil
}

func (x *RouteMessage) GetRouteUpdate() *RouteUpdate {
	if x != nil {
		if x, ok := x.Payload.(*RouteMessage_RouteUpdate); ok {
			return x.RouteUpdate
		}
	}
	return nil
}

func (x *RouteMessage) GetEndSnapshot() *EndSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*RouteMessage_EndSnapshot); ok {
			return x.EndSnapshot
		}
	}
	return nil
}

type isRouteMessage_Payload interface {
	isRouteMessage_Payload()
}

type RouteMessage_BeginSnapshot struct {
	// Marks the start of a full RIB snapshot for one router session.
	BeginSnapshot *BeginSnapshot `protobuf:"bytes,1,opt,name=begin_snapshot,json=beginSnapshot,proto3,oneof"`
}

type RouteMessage_RouteUpdate struct {
	// Carries one or more route additions or withdrawals.
	RouteUpdate *RouteUpdate `protobuf:"bytes,2,opt,name=route_update,json=routeUpdate,proto3,oneof"`
}

type RouteMessage_EndSnapshot struct {
	// Marks the end of a full RIB snapshot.
	EndSnapshot *EndSnapshot `protobuf:"bytes,3,opt,name=end_snapshot,json=endSnapshot,proto3,oneof"`
}

func (*RouteMessage_BeginSnapshot) isRouteMessage_Payload() {}

func (*RouteMessage_RouteUpdate) isRouteMessage_Payload() {}

func (*RouteMessage_EndSnapshot) isRouteMessage_Payload() {}

// BeginSnapshot signals that the collector is about to send the complete
// routing table for the given router session. Central should prepare to
// replace any previously held state.
type BeginSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The router session whose RIB is being transmitted.
	RouterSessionId string `protobuf:"bytes,1,opt,name=router_session_id,json=routerSessionId,proto3" json:"router_session_id,omitempty"`
	// Wall-clock time at which the snapshot was captured.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginSnapshot) Reset() {
	*x = BeginSnapshot{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginSnapshot) ProtoMessage() {}

func (x *BeginSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginSnapshot.ProtoReflect.Descriptor instead.
func (*BeginSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{4}
}

func (x *BeginSnapshot) GetRouterSessionId() string {
	if x != nil {
		return x.RouterSessionId
	}
	return ""
}

func (x *BeginSnapshot) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// RouteUpdate carries a batch of route changes for a single router session.
// During a snapshot every update is an ADD; after the snapshot, both ADD and
// WITHDRAW actions occur.
type RouteUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The router session this update belongs to.
	RouterSessionId string `protobuf:"bytes,1,opt,name=router_session_id,json=routerSessionId,proto3" json:"router_session_id,omitempty"`
	// Whether routes in this batch are being announced or withdrawn.
	Action RouteAction `protobuf:"varint,2,opt,name=action,proto3,enum=routebeacon.v1.RouteAction" json:"action,omitempty"`
	// One or more routes sharing the same action.
	Routes        []*BGPRoute `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdate) Reset() {
	*x = RouteUpdate{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdate) ProtoMessage() {}

func (x *RouteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdate.ProtoReflect.Descriptor instead.
func (*RouteUpdate) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{5}
}

func (x *RouteUpdate) GetRouterSessionId() string {
	if x != nil {
		return x.RouterSessionId
	}
	return ""
}

func (x *RouteUpdate) GetAction() RouteAction {
	if x != nil {
		return x.Action
	}
	return RouteAction_ROUTE_ACTION_UNSPECIFIED
}

func (x *RouteUpdate) GetRoutes() []*BGPRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

// EndSnapshot tells central that the full RIB dump for a session is
// complete. The route_count field lets central verify it received every
// route.
type EndSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The router session whose snapshot just finished.
	RouterSessionId string `protobuf:"bytes,1,opt,name=router_session_id,json=routerSessionId,proto3" json:"router_session_id,omitempty"`
	// Total number of routes the collector sent in this snapshot, used for
	// consistency verification.
	RouteCount    uint32 `protobuf:"varint,2,opt,name=route_count,json=routeCount,proto3" json:"route_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSnapshot) Reset() {
	*x = EndSnapshot{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSnapshot) ProtoMessage() {}

func (x *EndSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSnapshot.ProtoReflect.Descriptor instead.
func (*EndSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{6}
}

func (x *EndSnapshot) GetRouterSessionId() string {
	if x != nil {
		return x.RouterSessionId
	}
	return ""
}

func (x *EndSnapshot) GetRouteCount() uint32 {
	if x != nil {
		return x.RouteCount
	}
	return 0
}

// SyncControl is the envelope sent by central on the SyncRoutes return
// channel. Central uses it either to acknowledge snapshots or to apply
// back-pressure.
type SyncControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncControl_SnapshotAck
	//	*SyncControl_Throttle
	Payload       isSyncControl_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncControl) Reset() {
	*x = SyncControl{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncControl) ProtoMessage() {}

func (x *SyncControl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncControl.ProtoReflect.Descriptor instead.
func (*SyncControl) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{7}
}

func (x *SyncControl) GetPayload() isSyncControl_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncControl) GetSnapshotAck() *SnapshotAck {
	if x != nil {
		if x, ok := x.Payload.(*SyncControl_SnapshotAck); ok {
			return x.SnapshotAck
		}
	}
	return nil
}

func (x *SyncControl) GetThrottle() *Throttle {
	if x != nil {
		if x, ok := x.Payload.(*SyncControl_Throttle); ok {
			return x.Throttle
		}
	}
	return nil
}

type isSyncControl_Payload interface {
	isSyncControl_Payload()
}

type SyncControl_SnapshotAck struct {
	// Acknowledges successful receipt of a full snapshot.
	SnapshotAck *SnapshotAck `protobuf:"bytes,1,opt,name=snapshot_ack,json=snapshotAck,proto3,oneof"`
}

type SyncControl_Throttle struct {
	// Asks the collector to slow down its send rate.
	Throttle *Throttle `protobuf:"bytes,2,opt,name=throttle,proto3,oneof"`
}

func (*SyncControl_SnapshotAck) isSyncControl_Payload() {}

func (*SyncControl_Throttle) isSyncControl_Payload() {}

// SnapshotAck confirms that central has ingested a complete snapshot for
// a router session.
type SnapshotAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session whose snapshot was acknowledged.
	RouterSessionId string `protobuf:"bytes,1,opt,name=router_session_id,json=routerSessionId,proto3" json:"router_session_id,omitempty"`
	// Number of routes central actually stored; the collector can compare
	// this against its own count to detect loss.
	RoutesReceived uint32 `protobuf:"varint,2,opt,name=routes_received,json=routesReceived,proto3" json:"routes_received,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SnapshotAck) Reset() {
	*x = SnapshotAck{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotAck) ProtoMessage() {}

func (x *SnapshotAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotAck.ProtoReflect.Descriptor instead.
func (*SnapshotAck) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotAck) GetRouterSessionId() string {
	if x != nil {
		return x.RouterSessionId
	}
	return ""
}

func (x *SnapshotAck) GetRoutesReceived() uint32 {
	if x != nil {
		return x.RoutesReceived
	}
	return 0
}

// Throttle instructs the collector to pause or slow down sending for the
// given duration. The collector should wait at least delay_ms milliseconds
// before sending the next RouteMessage.
type Throttle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum delay in milliseconds before the next send.
	DelayMs       uint32 `protobuf:"varint,1,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Throttle) Reset() {
	*x = Throttle{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Throttle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Throttle) ProtoMessage() {}

func (x *Throttle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Throttle.ProtoReflect.Descriptor instead.
func (*Throttle) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{9}
}

func (x *Throttle) GetDelayMs() uint32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

// BGPRoute represents a single entry in the BGP RIB.
type BGPRoute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network prefix in network byte order (4 bytes for IPv4, 16 for IPv6).
	Prefix []byte `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// CIDR prefix length (0-32 for IPv4, 0-128 for IPv6).
	PrefixLength uint32 `protobuf:"varint,2,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	// Address family of the prefix.
	Afi AddressFamily `protobuf:"varint,3,opt,name=afi,proto3,enum=routebeacon.v1.AddressFamily" json:"afi,omitempty"`
	// True if this route is the best path selected by the BGP decision process.
	IsBest bool `protobuf:"varint,4,opt,name=is_best,json=isBest,proto3" json:"is_best,omitempty"`
	// BGP Add-Path path identifier (RFC 7911). Zero when Add-Path is not in
	// use.
	PathId uint32 `protobuf:"varint,5,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	// The full set of BGP path attributes for this route.
	Attributes    *BGPAttributes `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BGPRoute) Reset() {
	*x = BGPRoute{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BGPRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BGPRoute) ProtoMessage() {}

func (x *BGPRoute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BGPRoute.ProtoReflect.Descriptor instead.
func (*BGPRoute) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{10}
}

func (x *BGPRoute) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *BGPRoute) GetPrefixLength() uint32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *BGPRoute) GetAfi() AddressFamily {
	if x != nil {
		return x.Afi
	}
	return AddressFamily_ADDRESS_FAMILY_UNSPECIFIED
}

func (x *BGPRoute) GetIsBest() bool {
	if x != nil {
		return x.IsBest
	}
	return false
}

func (x *BGPRoute) GetPathId() uint32 {
	if x != nil {
		return x.PathId
	}
	return 0
}

func (x *BGPRoute) GetAttributes() *BGPAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// BGPAttributes holds the path attributes associated with a BGP route.
type BGPAttributes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flattened AS_PATH as an ordered list of ASNs (convenience field that
	// expands all segments sequentially).
	AsPath []uint32 `protobuf:"varint,1,rep,packed,name=as_path,json=asPath,proto3" json:"as_path,omitempty"`
	// Structured AS_PATH preserving segment boundaries and types.
	AsPathSegments []*ASPathSegment `protobuf:"bytes,2,rep,name=as_path_segments,json=asPathSegments,proto3" json:"as_path_segments,omitempty"`
	// Next-hop address in network byte order.
	NextHop []byte `protobuf:"bytes,3,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	// ORIGIN attribute: 0 = IGP, 1 = EGP, 2 = INCOMPLETE.
	Origin uint32 `protobuf:"varint,4,opt,name=origin,proto3" json:"origin,omitempty"`
	// Multi-Exit Discriminator.
	Med uint32 `protobuf:"varint,5,opt,name=med,proto3" json:"med,omitempty"`
	// LOCAL_PREF value.
	LocalPref uint32 `protobuf:"varint,6,opt,name=local_pref,json=localPref,proto3" json:"local_pref,omitempty"`
	// Standard BGP communities encoded as 32-bit values (RFC 1997).
	// Each value packs the two 16-bit halves: (high << 16) | low.
	Communities []uint32 `protobuf:"varint,7,rep,packed,name=communities,proto3" json:"communities,omitempty"`
	// Extended communities as raw 8-byte values (RFC 4360).
	ExtCommunities [][]byte `protobuf:"bytes,8,rep,name=ext_communities,json=extCommunities,proto3" json:"ext_communities,omitempty"`
	// BGP Large Communities (RFC 8092).
	LargeCommunities []*LargeCommunity `protobuf:"bytes,9,rep,name=large_communities,json=largeCommunities,proto3" json:"large_communities,omitempty"`
	// AGGREGATOR attribute: ASN of the aggregating router.
	AggregatorAsn uint32 `protobuf:"varint,10,opt,name=aggregator_asn,json=aggregatorAsn,proto3" json:"aggregator_asn,omitempty"`
	// AGGREGATOR attribute: IP address of the aggregating router in network
	// byte order.
	AggregatorAddress []byte `protobuf:"bytes,11,opt,name=aggregator_address,json=aggregatorAddress,proto3" json:"aggregator_address,omitempty"`
	// ATOMIC_AGGREGATE flag (RFC 4271 section 5.1.6).
	AtomicAggregate bool `protobuf:"varint,12,opt,name=atomic_aggregate,json=atomicAggregate,proto3" json:"atomic_aggregate,omitempty"`
	// Explicit presence flag for MED.
	MedPresent bool `protobuf:"varint,13,opt,name=med_present,json=medPresent,proto3" json:"med_present,omitempty"`
	// Explicit presence flag for LOCAL_PREF.
	LocalPrefPresent bool `protobuf:"varint,14,opt,name=local_pref_present,json=localPrefPresent,proto3" json:"local_pref_present,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BGPAttributes) Reset() {
	*x = BGPAttributes{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BGPAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BGPAttributes) ProtoMessage() {}

func (x *BGPAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BGPAttributes.ProtoReflect.Descriptor instead.
func (*BGPAttributes) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{11}
}

func (x *BGPAttributes) GetAsPath() []uint32 {
	if x != nil {
		return x.AsPath
	}
	return nil
}

func (x *BGPAttributes) GetAsPathSegments() []*ASPathSegment {
	if x != nil {
		return x.AsPathSegments
	}
	return nil
}

func (x *BGPAttributes) GetNextHop() []byte {
	if x != nil {
		return x.NextHop
	}
	return nil
}

func (x *BGPAttributes) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *BGPAttributes) GetMed() uint32 {
	if x != nil {
		return x.Med
	}
	return 0
}

func (x *BGPAttributes) GetLocalPref() uint32 {
	if x != nil {
		return x.LocalPref
	}
	return 0
}

func (x *BGPAttributes) GetCommunities() []uint32 {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *BGPAttributes) GetExtCommunities() [][]byte {
	if x != nil {
		return x.ExtCommunities
	}
	return nil
}

func (x *BGPAttributes) GetLargeCommunities() []*LargeCommunity {
	if x != nil {
		return x.LargeCommunities
	}
	return nil
}

func (x *BGPAttributes) GetAggregatorAsn() uint32 {
	if x != nil {
		return x.AggregatorAsn
	}
	return 0
}

func (x *BGPAttributes) GetAggregatorAddress() []byte {
	if x != nil {
		return x.AggregatorAddress
	}
	return nil
}

func (x *BGPAttributes) GetAtomicAggregate() bool {
	if x != nil {
		return x.AtomicAggregate
	}
	return false
}

func (x *BGPAttributes) GetMedPresent() bool {
	if x != nil {
		return x.MedPresent
	}
	return false
}

func (x *BGPAttributes) GetLocalPrefPresent() bool {
	if x != nil {
		return x.LocalPrefPresent
	}
	return false
}

// ASPathSegment represents a single segment of the AS_PATH attribute,
// preserving the distinction between AS_SET and AS_SEQUENCE.
type ASPathSegment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of this segment.
	Type ASPathSegmentType `protobuf:"varint,1,opt,name=type,proto3,enum=routebeacon.v1.ASPathSegmentType" json:"type,omitempty"`
	// ASNs contained in this segment.
	Numbers       []uint32 `protobuf:"varint,2,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASPathSegment) Reset() {
	*x = ASPathSegment{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASPathSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASPathSegment) ProtoMessage() {}

func (x *ASPathSegment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASPathSegment.ProtoReflect.Descriptor instead.
func (*ASPathSegment) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{12}
}

func (x *ASPathSegment) GetType() ASPathSegmentType {
	if x != nil {
		return x.Type
	}
	return ASPathSegmentType_AS_PATH_SEGMENT_TYPE_UNSPECIFIED
}

func (x *ASPathSegment) GetNumbers() []uint32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

// LargeCommunity represents a single BGP Large Community (RFC 8092) with
// three 32-bit fields.
type LargeCommunity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalAdmin   uint32                 `protobuf:"varint,1,opt,name=global_admin,json=globalAdmin,proto3" json:"global_admin,omitempty"`
	LocalData_1   uint32                 `protobuf:"varint,2,opt,name=local_data_1,json=localData1,proto3" json:"local_data_1,omitempty"`
	LocalData_2   uint32                 `protobuf:"varint,3,opt,name=local_data_2,json=localData2,proto3" json:"local_data_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LargeCommunity) Reset() {
	*x = LargeCommunity{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargeCommunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeCommunity) ProtoMessage() {}

func (x *LargeCommunity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeCommunity.ProtoReflect.Descriptor instead.
func (*LargeCommunity) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{13}
}

func (x *LargeCommunity) GetGlobalAdmin() uint32 {
	if x != nil {
		return x.GlobalAdmin
	}
	return 0
}

func (x *LargeCommunity) GetLocalData_1() uint32 {
	if x != nil {
		return x.LocalData_1
	}
	return 0
}

func (x *LargeCommunity) GetLocalData_2() uint32 {
	if x != nil {
		return x.LocalData_2
	}
	return 0
}

// CollectorIdentity identifies the calling collector on the SubscribeCommands
// stream.
type CollectorIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The collector's unique identifier, matching the value sent in Register.
	CollectorId   string `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorIdentity) Reset() {
	*x = CollectorIdentity{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorIdentity) ProtoMessage() {}

func (x *CollectorIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorIdentity.ProtoReflect.Descriptor instead.
func (*CollectorIdentity) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{14}
}

func (x *CollectorIdentity) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

// DiagnosticCommand is a single command pushed by central for the collector
// to execute against one of its router sessions.
type DiagnosticCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this command invocation, used to correlate results.
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// The router session that should execute the command.
	RouterSessionId string `protobuf:"bytes,2,opt,name=router_session_id,json=routerSessionId,proto3" json:"router_session_id,omitempty"`
	// The specific command to run.
	//
	// Types that are valid to be assigned to Command:
	//
	//	*DiagnosticCommand_Ping
	//	*DiagnosticCommand_Traceroute
	Command       isDiagnosticCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticCommand) Reset() {
	*x = DiagnosticCommand{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticCommand) ProtoMessage() {}

func (x *DiagnosticCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticCommand.ProtoReflect.Descriptor instead.
func (*DiagnosticCommand) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{15}
}

func (x *DiagnosticCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DiagnosticCommand) GetRouterSessionId() string {
	if x != nil {
		return x.RouterSessionId
	}
	return ""
}

func (x *DiagnosticCommand) GetCommand() isDiagnosticCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *DiagnosticCommand) GetPing() *PingCommand {
	if x != nil {
		if x, ok := x.Command.(*DiagnosticCommand_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *DiagnosticCommand) GetTraceroute() *TracerouteCommand {
	if x != nil {
		if x, ok := x.Command.(*DiagnosticCommand_Traceroute); ok {
			return x.Traceroute
		}
	}
	return nil
}

type isDiagnosticCommand_Command interface {
	isDiagnosticCommand_Command()
}

type DiagnosticCommand_Ping struct {
	Ping *PingCommand `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type DiagnosticCommand_Traceroute struct {
	Traceroute *TracerouteCommand `protobuf:"bytes,4,opt,name=traceroute,proto3,oneof"`
}

func (*DiagnosticCommand_Ping) isDiagnosticCommand_Command() {}

func (*DiagnosticCommand_Traceroute) isDiagnosticCommand_Command() {}

// PingCommand asks the collector to perform an ICMP echo toward a
// destination via the specified router session.
type PingCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target IP address (IPv4 or IPv6 in text form).
	Destination string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	// Number of echo requests to send.
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Per-probe timeout in milliseconds.
	TimeoutMs     uint32 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingCommand) Reset() {
	*x = PingCommand{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCommand) ProtoMessage() {}

func (x *PingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCommand.ProtoReflect.Descriptor instead.
func (*PingCommand) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{16}
}

func (x *PingCommand) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *PingCommand) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PingCommand) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// TracerouteCommand asks the collector to trace the path toward a
// destination via the specified router session.
type TracerouteCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target IP address (IPv4 or IPv6 in text form).
	Destination string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	// Maximum number of hops (TTL limit).
	MaxHops uint32 `protobuf:"varint,2,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	// Per-probe timeout in milliseconds.
	TimeoutMs     uint32 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracerouteCommand) Reset() {
	*x = TracerouteCommand{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteCommand) ProtoMessage() {}

func (x *TracerouteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteCommand.ProtoReflect.Descriptor instead.
func (*TracerouteCommand) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{17}
}

func (x *TracerouteCommand) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *TracerouteCommand) GetMaxHops() uint32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *TracerouteCommand) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// CommandResultChunk carries one piece of output from a diagnostic command.
// The collector sends a stream of these, ending with either CommandComplete
// or CommandError.
type CommandResultChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The command_id this result belongs to.
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Exactly one result type per chunk.
	//
	// Types that are valid to be assigned to Result:
	//
	//	*CommandResultChunk_PingResult
	//	*CommandResultChunk_TracerouteHop
	//	*CommandResultChunk_Complete
	//	*CommandResultChunk_Error
	Result        isCommandResultChunk_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResultChunk) Reset() {
	*x = CommandResultChunk{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResultChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResultChunk) ProtoMessage() {}

func (x *CommandResultChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResultChunk.ProtoReflect.Descriptor instead.
func (*CommandResultChunk) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{18}
}

func (x *CommandResultChunk) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResultChunk) GetResult() isCommandResultChunk_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResultChunk) GetPingResult() *PingResult {
	if x != nil {
		if x, ok := x.Result.(*CommandResultChunk_PingResult); ok {
			return x.PingResult
		}
	}
	return nil
}

func (x *CommandResultChunk) GetTracerouteHop() *TracerouteHop {
	if x != nil {
		if x, ok := x.Result.(*CommandResultChunk_TracerouteHop); ok {
			return x.TracerouteHop
		}
	}
	return nil
}

func (x *CommandResultChunk) GetComplete() *CommandComplete {
	if x != nil {
		if x, ok := x.Result.(*CommandResultChunk_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *CommandResultChunk) GetError() *CommandError {
	if x != nil {
		if x, ok := x.Result.(*CommandResultChunk_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCommandResultChunk_Result interface {
	isCommandResultChunk_Result()
}

type CommandResultChunk_PingResult struct {
	// A single ICMP echo reply (or timeout).
	PingResult *PingResult `protobuf:"bytes,2,opt,name=ping_result,json=pingResult,proto3,oneof"`
}

type CommandResultChunk_TracerouteHop struct {
	// A single traceroute hop.
	TracerouteHop *TracerouteHop `protobuf:"bytes,3,opt,name=traceroute_hop,json=tracerouteHop,proto3,oneof"`
}

type CommandResultChunk_Complete struct {
	// Signals successful completion of the command.
	Complete *CommandComplete `protobuf:"bytes,4,opt,name=complete,proto3,oneof"`
}

type CommandResultChunk_Error struct {
	// Signals that the command failed.
	Error *CommandError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*CommandResultChunk_PingResult) isCommandResultChunk_Result() {}

func (*CommandResultChunk_TracerouteHop) isCommandResultChunk_Result() {}

func (*CommandResultChunk_Complete) isCommandResultChunk_Result() {}

func (*CommandResultChunk_Error) isCommandResultChunk_Result() {}

// PingResult reports the outcome of a single ICMP echo request.
type PingResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence number of the echo request (starting from 1).
	Sequence uint32 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Round-trip time in microseconds. Meaningful only when success is true.
	RttUs uint32 `protobuf:"varint,2,opt,name=rtt_us,json=rttUs,proto3" json:"rtt_us,omitempty"`
	// IP TTL of the echo reply.
	Ttl uint32 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// True if a reply was received before the timeout expired.
	Success       bool `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResult) Reset() {
	*x = PingResult{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResult) ProtoMessage() {}

func (x *PingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResult.ProtoReflect.Descriptor instead.
func (*PingResult) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{19}
}

func (x *PingResult) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PingResult) GetRttUs() uint32 {
	if x != nil {
		return x.RttUs
	}
	return 0
}

func (x *PingResult) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *PingResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// TracerouteHop reports the result of probing one TTL value during a
// traceroute.
type TracerouteHop struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The TTL / hop number (starting from 1).
	HopNumber uint32 `protobuf:"varint,1,opt,name=hop_number,json=hopNumber,proto3" json:"hop_number,omitempty"`
	// IP address of the responding node (empty string if no response).
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Round-trip times in microseconds for each probe at this hop. Multiple
	// values correspond to multiple probes per TTL (commonly 3).
	RttUs         []uint32 `protobuf:"varint,3,rep,packed,name=rtt_us,json=rttUs,proto3" json:"rtt_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracerouteHop) Reset() {
	*x = TracerouteHop{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteHop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteHop) ProtoMessage() {}

func (x *TracerouteHop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteHop.ProtoReflect.Descriptor instead.
func (*TracerouteHop) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{20}
}

func (x *TracerouteHop) GetHopNumber() uint32 {
	if x != nil {
		return x.HopNumber
	}
	return 0
}

func (x *TracerouteHop) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TracerouteHop) GetRttUs() []uint32 {
	if x != nil {
		return x.RttUs
	}
	return nil
}

// CommandComplete signals that a diagnostic command finished successfully.
type CommandComplete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plain-text summary of the results (e.g. "5 packets sent, 5 received,
	// 0% loss, avg RTT 12.3 ms").
	Summary       string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandComplete) Reset() {
	*x = CommandComplete{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandComplete) ProtoMessage() {}

func (x *CommandComplete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandComplete.ProtoReflect.Descriptor instead.
func (*CommandComplete) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{21}
}

func (x *CommandComplete) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// CommandError signals that a diagnostic command failed.
type CommandError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine-readable error code (e.g. "TIMEOUT", "UNREACHABLE",
	// "SESSION_DOWN").
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error description.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandError) Reset() {
	*x = CommandError{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandError) ProtoMessage() {}

func (x *CommandError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandError.ProtoReflect.Descriptor instead.
func (*CommandError) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{22}
}

func (x *CommandError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CommandError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CommandAck is the final response from central after the collector closes
// the ReportCommandResult stream.
type CommandAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if central successfully processed all result chunks.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routebeacon_v1_collector_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP(), []int{23}
}

func (x *CommandAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_proto_routebeacon_v1_collector_service_proto protoreflect.FileDescriptor

const file_proto_routebeacon_v1_collector_service_proto_rawDesc = "" +
	"\n" +
	",proto/routebeacon/v1/collector_service.proto\x12\x0eroutebeacon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x01\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\x12#\n" +
	"\rlocation_name\x18\x02 \x01(\tR\flocationName\x12F\n" +
	"\x0frouter_sessions\x18\x03 \x03(\v2\x1d.routebeacon.v1.RouterSessionR\x0erouterSessions\"\x8e\x01\n" +
	"\rRouterSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03asn\x18\x03 \x01(\rR\x03asn\x12)\n" +
	"\x10neighbor_address\x18\x04 \x01(\tR\x0fneighborAddress\"H\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe5\x01\n" +
	"\fRouteMessage\x12F\n" +
	"\x0ebegin_snapshot\x18\x01 \x01(\v2\x1d.routebeacon.v1.BeginSnapshotH\x00R\rbeginSnapshot\x12@\n" +
	"\froute_update\x18\x02 \x01(\v2\x1b.routebeacon.v1.RouteUpdateH\x00R\vrouteUpdate\x12@\n" +
	"\fend_snapshot\x18\x03 \x01(\v2\x1b.routebeacon.v1.EndSnapshotH\x00R\vendSnapshotB\t\n" +
	"\apayload\"u\n" +
	"\rBeginSnapshot\x12*\n" +
	"\x11router_session_id\x18\x01 \x01(\tR\x0frouterSessionId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa0\x01\n" +
	"\vRouteUpdate\x12*\n" +
	"\x11router_session_id\x18\x01 \x01(\tR\x0frouterSessionId\x123\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1b.routebeacon.v1.RouteActionR\x06action\x120\n" +
	"\x06routes\x18\x03 \x03(\v2\x18.routebeacon.v1.BGPRouteR\x06routes\"Z\n" +
	"\vEndSnapshot\x12*\n" +
	"\x11router_session_id\x18\x01 \x01(\tR\x0frouterSessionId\x12\x1f\n" +
	"\vroute_count\x18\x02 \x01(\rR\n" +
	"routeCount\"\x92\x01\n" +
	"\vSyncControl\x12@\n" +
	"\fsnapshot_ack\x18\x01 \x01(\v2\x1b.routebeacon.v1.SnapshotAckH\x00R\vsnapshotAck\x126\n" +
	"\bthrottle\x18\x02 \x01(\v2\x18.routebeacon.v1.ThrottleH\x00R\bthrottleB\t\n" +
	"\apayload\"b\n" +
	"\vSnapshotAck\x12*\n" +
	"\x11router_session_id\x18\x01 \x01(\tR\x0frouterSessionId\x12'\n" +
	"\x0froutes_received\x18\x02 \x01(\rR\x0eroutesReceived\"%\n" +
	"\bThrottle\x12\x19\n" +
	"\bdelay_ms\x18\x01 \x01(\rR\adelayMs\"\xe9\x01\n" +
	"\bBGPRoute\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12#\n" +
	"\rprefix_length\x18\x02 \x01(\rR\fprefixLength\x12/\n" +
	"\x03afi\x18\x03 \x01(\x0e2\x1d.routebeacon.v1.AddressFamilyR\x03afi\x12\x17\n" +
	"\ais_best\x18\x04 \x01(\bR\x06isBest\x12\x17\n" +
	"\apath_id\x18\x05 \x01(\rR\x06pathId\x12=\n" +
	"\n" +
	"attributes\x18\x06 \x01(\v2\x1d.routebeacon.v1.BGPAttributesR\n" +
	"attributes\"\xee\x03\n" +
	"\rBGPAttributes\x12\x17\n" +
	"\aas_path\x18\x01 \x03(\rR\x06asPath\x12G\n" +
	"\x10as_path_segments\x18\x02 \x03(\v2\x1d.routebeacon.v1.ASPathSegmentR\x0easPathSegments\x12\x19\n" +
	"\bnext_hop\x18\x03 \x01(\fR\anextHop\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\rR\x06origin\x12\x10\n" +
	"\x03med\x18\x05 \x01(\rR\x03med\x12\x1d\n" +
	"\n" +
	"local_pref\x18\x06 \x01(\rR\tlocalPref\x12 \n" +
	"\vcommunities\x18\a \x03(\rR\vcommunities\x12'\n" +
	"\x0fext_communities\x18\b \x03(\fR\x0eextCommunities\x12K\n" +
	"\x11large_communities\x18\t \x03(\v2\x1e.routebeacon.v1.LargeCommunityR\x10largeCommunities\x12%\n" +
	"\x0eaggregator_asn\x18\n" +
	" \x01(\rR\raggregatorAsn\x12-\n" +
	"\x12aggregator_address\x18\v \x01(\fR\x11aggregatorAddress\x12)\n" +
	"\x10atomic_aggregate\x18\f \x01(\bR\x0fatomicAggregate\"`\n" +
	"\rASPathSegment\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.routebeacon.v1.ASPathSegmentTypeR\x04type\x12\x18\n" +
	"\anumbers\x18\x02 \x03(\rR\anumbers\"w\n" +
	"\x0eLargeCommunity\x12!\n" +
	"\fglobal_admin\x18\x01 \x01(\rR\vglobalAdmin\x12 \n" +
	"\flocal_data_1\x18\x02 \x01(\rR\n" +
	"localData1\x12 \n" +
	"\flocal_data_2\x18\x03 \x01(\rR\n" +
	"localData2\"6\n" +
	"\x11CollectorIdentity\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\"\xe1\x01\n" +
	"\x11DiagnosticCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12*\n" +
	"\x11router_session_id\x18\x02 \x01(\tR\x0frouterSessionId\x121\n" +
	"\x04ping\x18\x03 \x01(\v2\x1b.routebeacon.v1.PingCommandH\x00R\x04ping\x12C\n" +
	"\n" +
	"traceroute\x18\x04 \x01(\v2!.routebeacon.v1.TracerouteCommandH\x00R\n" +
	"tracerouteB\t\n" +
	"\acommand\"d\n" +
	"\vPingCommand\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\"o\n" +
	"\x11TracerouteCommand\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x19\n" +
	"\bmax_hops\x18\x02 \x01(\rR\amaxHops\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\"\xb9\x02\n" +
	"\x12CommandResultChunk\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12=\n" +
	"\vping_result\x18\x02 \x01(\v2\x1a.routebeacon.v1.PingResultH\x00R\n" +
	"pingResult\x12F\n" +
	"\x0etraceroute_hop\x18\x03 \x01(\v2\x1d.routebeacon.v1.TracerouteHopH\x00R\rtracerouteHop\x12=\n" +
	"\bcomplete\x18\x04 \x01(\v2\x1f.routebeacon.v1.CommandCompleteH\x00R\bcomplete\x124\n" +
	"\x05error\x18\x05 \x01(\v2\x1c.routebeacon.v1.CommandErrorH\x00R\x05errorB\b\n" +
	"\x06result\"k\n" +
	"\n" +
	"PingResult\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x12\x15\n" +
	"\x06rtt_us\x18\x02 \x01(\rR\x05rttUs\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\rR\x03ttl\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"_\n" +
	"\rTracerouteHop\x12\x1d\n" +
	"\n" +
	"hop_number\x18\x01 \x01(\rR\thopNumber\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x15\n" +
	"\x06rtt_us\x18\x03 \x03(\rR\x05rttUs\"+\n" +
	"\x0fCommandComplete\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\"<\n" +
	"\fCommandError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\n" +
	"CommandAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*B\n" +
	"\vRouteAction\x12\x1c\n" +
	"\x18ROUTE_ACTION_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ADD\x10\x01\x12\f\n" +
	"\bWITHDRAW\x10\x02*C\n" +
	"\rAddressFamily\x12\x1e\n" +
	"\x1aADDRESS_FAMILY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04IPV4\x10\x01\x12\b\n" +
	"\x04IPV6\x10\x02*V\n" +
	"\x11ASPathSegmentType\x12$\n" +
	" AS_PATH_SEGMENT_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06AS_SET\x10\x01\x12\x0f\n" +
	"\vAS_SEQUENCE\x10\x022\xe4\x02\n" +
	"\x10CollectorService\x12M\n" +
	"\bRegister\x12\x1f.routebeacon.v1.RegisterRequest\x1a .routebeacon.v1.RegisterResponse\x12K\n" +
	"\n" +
	"SyncRoutes\x12\x1c.routebeacon.v1.RouteMessage\x1a\x1b.routebeacon.v1.SyncControl(\x010\x01\x12[\n" +
	"\x11SubscribeCommands\x12!.routebeacon.v1.CollectorIdentity\x1a!.routebeacon.v1.DiagnosticCommand0\x01\x12W\n" +
	"\x13ReportCommandResult\x12\".routebeacon.v1.CommandResultChunk\x1a\x1a.routebeacon.v1.CommandAck(\x01B\x1eZ\x1croutebeacon/v1;routebeaconv1b\x06proto3"

var (
	file_proto_routebeacon_v1_collector_service_proto_rawDescOnce sync.Once
	file_proto_routebeacon_v1_collector_service_proto_rawDescData []byte
)

func file_proto_routebeacon_v1_collector_service_proto_rawDescGZIP() []byte {
	file_proto_routebeacon_v1_collector_service_proto_rawDescOnce.Do(func() {
		file_proto_routebeacon_v1_collector_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_routebeacon_v1_collector_service_proto_rawDesc), len(file_proto_routebeacon_v1_collector_service_proto_rawDesc)))
	})
	return file_proto_routebeacon_v1_collector_service_proto_rawDescData
}

var file_proto_routebeacon_v1_collector_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_routebeacon_v1_collector_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_routebeacon_v1_collector_service_proto_goTypes = []any{
	(RouteAction)(0),              // 0: routebeacon.v1.RouteAction
	(AddressFamily)(0),            // 1: routebeacon.v1.AddressFamily
	(ASPathSegmentType)(0),        // 2: routebeacon.v1.ASPathSegmentType
	(*RegisterRequest)(nil),       // 3: routebeacon.v1.RegisterRequest
	(*RouterSession)(nil),         // 4: routebeacon.v1.RouterSession
	(*RegisterResponse)(nil),      // 5: routebeacon.v1.RegisterResponse
	(*RouteMessage)(nil),          // 6: routebeacon.v1.RouteMessage
	(*BeginSnapshot)(nil),         // 7: routebeacon.v1.BeginSnapshot
	(*RouteUpdate)(nil),           // 8: routebeacon.v1.RouteUpdate
	(*EndSnapshot)(nil),           // 9: routebeacon.v1.EndSnapshot
	(*SyncControl)(nil),           // 10: routebeacon.v1.SyncControl
	(*SnapshotAck)(nil),           // 11: routebeacon.v1.SnapshotAck
	(*Throttle)(nil),              // 12: routebeacon.v1.Throttle
	(*BGPRoute)(nil),              // 13: routebeacon.v1.BGPRoute
	(*BGPAttributes)(nil),         // 14: routebeacon.v1.BGPAttributes
	(*ASPathSegment)(nil),         // 15: routebeacon.v1.ASPathSegment
	(*LargeCommunity)(nil),        // 16: routebeacon.v1.LargeCommunity
	(*CollectorIdentity)(nil),     // 17: routebeacon.v1.CollectorIdentity
	(*DiagnosticCommand)(nil),     // 18: routebeacon.v1.DiagnosticCommand
	(*PingCommand)(nil),           // 19: routebeacon.v1.PingCommand
	(*TracerouteCommand)(nil),     // 20: routebeacon.v1.TracerouteCommand
	(*CommandResultChunk)(nil),    // 21: routebeacon.v1.CommandResultChunk
	(*PingResult)(nil),            // 22: routebeacon.v1.PingResult
	(*TracerouteHop)(nil),         // 23: routebeacon.v1.TracerouteHop
	(*CommandComplete)(nil),       // 24: routebeacon.v1.CommandComplete
	(*CommandError)(nil),          // 25: routebeacon.v1.CommandError
	(*CommandAck)(nil),            // 26: routebeacon.v1.CommandAck
	(*timestamppb.Timestamp)(nil), // 27: google.protobuf.Timestamp
}
var file_proto_routebeacon_v1_collector_service_proto_depIdxs = []int32{
	4,  // 0: routebeacon.v1.RegisterRequest.router_sessions:type_name -> routebeacon.v1.RouterSession
	7,  // 1: routebeacon.v1.RouteMessage.begin_snapshot:type_name -> routebeacon.v1.BeginSnapshot
	8,  // 2: routebeacon.v1.RouteMessage.route_update:type_name -> routebeacon.v1.RouteUpdate
	9,  // 3: routebeacon.v1.RouteMessage.end_snapshot:type_name -> routebeacon.v1.EndSnapshot
	27, // 4: routebeacon.v1.BeginSnapshot.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 5: routebeacon.v1.RouteUpdate.action:type_name -> routebeacon.v1.RouteAction
	13, // 6: routebeacon.v1.RouteUpdate.routes:type_name -> routebeacon.v1.BGPRoute
	11, // 7: routebeacon.v1.SyncControl.snapshot_ack:type_name -> routebeacon.v1.SnapshotAck
	12, // 8: routebeacon.v1.SyncControl.throttle:type_name -> routebeacon.v1.Throttle
	1,  // 9: routebeacon.v1.BGPRoute.afi:type_name -> routebeacon.v1.AddressFamily
	14, // 10: routebeacon.v1.BGPRoute.attributes:type_name -> routebeacon.v1.BGPAttributes
	15, // 11: routebeacon.v1.BGPAttributes.as_path_segments:type_name -> routebeacon.v1.ASPathSegment
	16, // 12: routebeacon.v1.BGPAttributes.large_communities:type_name -> routebeacon.v1.LargeCommunity
	2,  // 13: routebeacon.v1.ASPathSegment.type:type_name -> routebeacon.v1.ASPathSegmentType
	19, // 14: routebeacon.v1.DiagnosticCommand.ping:type_name -> routebeacon.v1.PingCommand
	20, // 15: routebeacon.v1.DiagnosticCommand.traceroute:type_name -> routebeacon.v1.TracerouteCommand
	22, // 16: routebeacon.v1.CommandResultChunk.ping_result:type_name -> routebeacon.v1.PingResult
	23, // 17: routebeacon.v1.CommandResultChunk.traceroute_hop:type_name -> routebeacon.v1.TracerouteHop
	24, // 18: routebeacon.v1.CommandResultChunk.complete:type_name -> routebeacon.v1.CommandComplete
	25, // 19: routebeacon.v1.CommandResultChunk.error:type_name -> routebeacon.v1.CommandError
	3,  // 20: routebeacon.v1.CollectorService.Register:input_type -> routebeacon.v1.RegisterRequest
	6,  // 21: routebeacon.v1.CollectorService.SyncRoutes:input_type -> routebeacon.v1.RouteMessage
	17, // 22: routebeacon.v1.CollectorService.SubscribeCommands:input_type -> routebeacon.v1.CollectorIdentity
	21, // 23: routebeacon.v1.CollectorService.ReportCommandResult:input_type -> routebeacon.v1.CommandResultChunk
	5,  // 24: routebeacon.v1.CollectorService.Register:output_type -> routebeacon.v1.RegisterResponse
	10, // 25: routebeacon.v1.CollectorService.SyncRoutes:output_type -> routebeacon.v1.SyncControl
	18, // 26: routebeacon.v1.CollectorService.SubscribeCommands:output_type -> routebeacon.v1.DiagnosticCommand
	26, // 27: routebeacon.v1.CollectorService.ReportCommandResult:output_type -> routebeacon.v1.CommandAck
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_routebeacon_v1_collector_service_proto_init() }
func file_proto_routebeacon_v1_collector_service_proto_init() {
	if File_proto_routebeacon_v1_collector_service_proto != nil {
		return
	}
	file_proto_routebeacon_v1_collector_service_proto_msgTypes[3].OneofWrappers = []any{
		(*RouteMessage_BeginSnapshot)(nil),
		(*RouteMessage_RouteUpdate)(nil),
		(*RouteMessage_EndSnapshot)(nil),
	}
	file_proto_routebeacon_v1_collector_service_proto_msgTypes[7].OneofWrappers = []any{
		(*SyncControl_SnapshotAck)(nil),
		(*SyncControl_Throttle)(nil),
	}
	file_proto_routebeacon_v1_collector_service_proto_msgTypes[15].OneofWrappers = []any{
		(*DiagnosticCommand_Ping)(nil),
		(*DiagnosticCommand_Traceroute)(nil),
	}
	file_proto_routebeacon_v1_collector_service_proto_msgTypes[18].OneofWrappers = []any{
		(*CommandResultChunk_PingResult)(nil),
		(*CommandResultChunk_TracerouteHop)(nil),
		(*CommandResultChunk_Complete)(nil),
		(*CommandResultChunk_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_routebeacon_v1_collector_service_proto_rawDesc), len(file_proto_routebeacon_v1_collector_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_routebeacon_v1_collector_service_proto_goTypes,
		DependencyIndexes: file_proto_routebeacon_v1_collector_service_proto_depIdxs,
		EnumInfos:         file_proto_routebeacon_v1_collector_service_proto_enumTypes,
		MessageInfos:      file_proto_routebeacon_v1_collector_service_proto_msgTypes,
	}.Build()
	File_proto_routebeacon_v1_collector_service_proto = out.File
	file_proto_routebeacon_v1_collector_service_proto_goTypes = nil
	file_proto_routebeacon_v1_collector_service_proto_depIdxs = nil
}
